name: Run All Tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: npm install
            - name: Build the Project
              run: npm run build
            - name: Run tests
              run: npm run test
