name: Hello World

on:
    push:
        branches:
            - main

jobs:
    hello:

        runs-on: ubuntu-latest

        steps:
            - name: Display hello world
              run: echo "Hello, World"